### ISSUE TITLE
[QUESTION] Performance

### ISSUE THREAD

**Issue by Jeroen-G** [spatie/html-element#1]
I was wondering, to which extent does this way affect the performance and loading of the page in comparison to plain html. Although I suppose caching would level this out.

**Comment by sebastiandedeyne** [comment]
Honestly, I don't really know the performance implications, would need some benchmarking for that. My use case for this package is for smaller chunks of html that contain a lot of dynamic attributes, not to replace an entire templating system.

If I've got some free time on my hands, I might give Blackfire a shot to get some metrics.
