### ISSUE TITLE
please release a patch for php8.0

### ISSUE THREAD

**Issue by devsrv** [spatie/html-element#17]
latest release supports php7 only

**Comment by freekmurze** [comment]
Done

**Comment by devsrv** [comment]
you are ❤ 🙏

**Comment by devsrv** [comment]
Hi @freekmurze packagist not yet recognized about the release ☹ https://packagist.org/packages/spatie/html-element

**Comment by freekmurze** [comment]
This has been fixed!




Freek Van der Herten
https://spatie.be
