### ISSUE TITLE
**[BUG]** Value "0" is ignored in rendered HTML Tag Attributes

### ISSUE THREAD

**Issue by klor** [spatie/html-element#3]
Hello, 

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have checked that the bug-fix I am reporting can be replicated.

---

I am trying to render a HTML SELECT OPTION tag programmatically. As it turns out, the value "0" is ignored when used as an attribute value, as shown here:

```php
$attr = ['name'=>'foo', 'value'=>'0', 'label'=>'Foo'];
echo el('option', $attr, $attr['label']);
// Observed output: <option name="foo" value label="Foo">Foo</option>
// Expected output: <option name="foo" value="0" label="Foo">Foo</option>
```

It most likely happens because [the value "0" is treated as empty](http://stackoverflow.com/questions/2220519/in-php-is-0-treated-as-empty) (both the string "0" and the number 0).

Here is also a working example:

```php
$attr = ['name'=>'foo', 'value'=>'1', 'label'=>'Foo'];
echo el('option', $attr, $attr['label']);
// Works fine, the observed and expected output is: <option name="foo" value="1" label="Foo">Foo</option>
```

How do I get the expected output when using value=0?

### Steps to reproduce

Full code to recreate:

	<?php
	require './html-element/html-element.php';

	$attr = ['name'=>'foo', 'value'=>'0', 'label'=>'Foo'];
	echo el('option', $attr, $attr['label']);
	// Observed output: <option name="foo" value label="Foo">Foo</option>
	// Expected output: <option name="foo" value="0" label="Foo">Foo</option>

el() is defined this way:

	require 'src/HtmlElement.php';
	require 'src/Attributes.php';
	require 'src/AbbreviationParser.php';
	require 'src/TagRenderer.php';
	require 'src/Helpers/Arr.php';

	function el(string $tag, $attributes = null, $content = null) : string {
		return \Spatie\HtmlElement\HtmlElement::render(...func_get_args());
	}

**Comment by sebastiandedeyne** [comment]
Thanks for the detailed report!

Tagged a fix in version 1.0.1 :)
